### PR TITLE
Revert "Change params.py to params.json"

### PR DESCRIPTION
**Pull request by nieznanysprawiciel**
Reverts golemfactory/golem-verificator#93

### CODE REVIEW

**Comment by maaktweluit** [comment]
@nieznanysprawiciel What was wrong with this fix?

**Comment by nieznanysprawiciel** [comment]
There's nothing wrong, but we must ensure that our pull request to main golem repo will be merged first. I merged our changes to verificator already, but PR to golem is not ready.

**Comment by maaktweluit** [comment]
As far as i know the only thing pending on the golem main repo is a Golem-Verificator release.

I took this issue over because @Krigpl is on holiday

**Comment by nieznanysprawiciel** [comment]
There's our (I mean CGI team) pull request https://github.com/golemfactory/golem/pull/3626 pending.
Golem-verificator 1.6.4 is already published with our changes, so we can't publish new release of verificator, before we merge our PR to golem repo.
I will merge this PR as soon as we can ;)

**Comment by maaktweluit** [comment]
Clear, thanks for the info!

Let me know when you are ready to make a 1.6.5 version :)

**Pull request closed without merging**
